### ISSUE TITLE
advise: provide options to hide weekday and time

### ISSUE THREAD

**Issue by TooBug** [djyde/Cultus#3]
I hope there is a option to hide weekday and time.

BTW: Beautiful!!

**Comment by djyde** [comment]
Providing preference is a plan of the next version

**Comment by djyde** [comment]
Hey, TooBug.

I'm happy to tell you I'd achieve your advise now. Additionally, you can custom the menubar title by yourself (Support `moment.js` formatting)!

![image](https://cloud.githubusercontent.com/assets/914329/11038098/3dca71c2-873c-11e5-98e3-b7cdb3b74f61.png)

Waiting for the `1.1.0` releasing :) Or build the `dev` branch if you can't wait :D

**Comment by TooBug** [comment]
Sweet! Thank you!
